- name: Install Apache
  hosts: worker1
  become: yes
  vars_files:
  - vars/sudo_password.yml

  tasks:
  - name: Print host os family
    debug:
      msg: "This is an {{ansible_os_family}} system"

  - name: Install Apache using yum module
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install apache using apt module
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Print host service manager
    debug:
      msg: "Host service manager is: {{ ansible_service_mgr }}"

  - name: Start and enable Apache on RedHat family
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: Start and enable Apache on Debian family
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: Deploy custom HTML file
    copy:
      src: files/index.html
      dest: /var/www/html/index.html
      mode: '0644'
