- name: Installing Mysql and dependencies
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
  - mysql-server
  - mysql-client
  - python3-mysqldb
  - libmysqlclient-dev
  become: true
  notify: Start MySQL
